### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by rufuspollock** [datasets/geo-boundaries-world-110m#2]
Really needs fleshing out e.g.
- Summary needs a bit more saying where data came from and that this is geojson
- Data section explaining this comes from natural earth
- License section clarifying license

**Comment by jalbertbowden** [comment]
Also wondering if this can be closed because a) looks like an attempt was already made and b) this dataset has been deprecated.

**Comment by rufuspollock** [comment]
INVALID. As per @jalbertbowden this is deprecated.
