### ISSUE TITLE
Duplicate of https://github.com/datasets/geo-countries?

### ISSUE THREAD

**Issue by rufuspollock** [datasets/geo-boundaries-world-110m#3]
@lexman is now a duplicate of https://github.com/datasets/geo-countries?

If so we should just mark as deprecated ...

**Comment by lexman** [comment]
I've put a deprecation notice in the doc. Is there a more formal mecanism inside the datapackage itself ?

**Comment by rufuspollock** [comment]
@lexman no and it seems this was never properly published afaict so we are ok. I have also marked as deprecated in the repo's description.

**Comment by rufuspollock** [comment]
FIXED.
